### ISSUE TITLE
I have a core-dump back trace, what's the possible reason?

### ISSUE THREAD

**Issue by wangty6** [nmslib/hnsw#26]
`
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000fddfae in hnswlib::HierarchicalNSW<float>::searchBaseLayerST(unsigned int, void*, unsigned long) () at /home/bigo/recommend/recsys_framework/thirdparty/include/hnsw/hnswalg.h:253

#1  0x0000000000fdc8e3 in hnswlib::HierarchicalNSW<float>::searchKnn(void*, unsigned long) () at /home/bigo/recommend/recsys_framework/thirdparty/include/hnsw/hnswalg.h:704

#2  0x0000000000fdafc7 in brec::KnnIndex<float>::knnQuery(std::vector<std::pair<float, unsigned long>, std::allocator<std::pair<float, unsigned long> > >&, std::vector<float, std::allocator<float> > const&, unsigned long) () at /home/bigo/recommend/recsys_framework/brec/knn/knn_index.h:217

#3  0x0000000000fd90f1 in server::recsys::KnnModel::knnQuery(std::vector<std::pair<float, unsigned long>, std::allocator<std::pair<float, unsigned long> > >&, std::vector<float, std::allocator<float> > const&, int) () at /home/bigo/recommend/recommend_recall_d/src/models/knn_model.cpp:51
`

**Comment by wangty6** [comment]
I know it's because the graph is empty
